#!/bin/bash

exec > >(tee -i install.log) 2>&1

set -euxo pipefail

function erreur {
    tput setaf 1
    echo "Erreur : $1"
    echo "Veillez contactez l'Editeur "
    echo "Email : james.gbetchedji@epitech.eu"
    echo "Tel : +22956549199"
    tput sgr0
    exit 1
}

echo "INSTALLING TOOLS AND PACKAGES FOR EPITECH'S DUMP"
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

add-apt-repository -y -s universe
apt update
apt upgrade -y

echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections

packages_list=(
    avr-libc
    build-essential
    ca-certificates-java
    cabal-install
    cargo
    clang
    clang-tools
    cmake
    curl
    diffutils
    docker-compose
    docker.io
    elfutils
    elpa-tuareg
    emacs-nox
    ffmpeg
    flac
    gcovr
    ghc
    golang
    haskell-stack
    ksh
    liballegro5-dev
    libboost1.74-all-dev
    libc-bin
    libc-dev-bin
    libc-devtools
    libc6
    libc6-dbg
    libcsfml-dev
    libcsfml-doc
    libcunit1
    libcunit1-dev
    libelf-dev
    libfreetype-dev
    libgmp-dev
    libgmp10
    libgmp10-doc
    libgmp3-dev
    libgmpxx4ldbl
    libgudev-1.0-dev
    libirrlicht-dev
    libirrlicht1.8
    libjpeg-turbo8-dev
    libncurses-dev
    libopenal-dev
    libsdl2-dev
    libsfml-doc
    libuuid1
    libvirt-dev
    libvorbis-dev
    libx11-doc
    libx11-xcb-dev
    libxcb-image0
    libxcb-image0-dev
    libxcb-util-dev
    libxcb-util0-dev
    libxcb-util1
    libxcursor-dev
    libxext-dev
    libxext-doc
    libxi-dev
    libxinerama-dev
    libxrandr-dev
    locales
    ltrace
    mariadb-server
    nasm
    ncurses-base
    net-tools
    npm
    nodejs
    openjdk-21-jdk
    openjdk-21-jre
    php-bcmath
    php-dev
    php-gd
    php-mbstring
    php-mysql
    php-phar-io-version
    php-php-gettext
    php-tokenizer
    python3
    python3-pycryptodome
    python3-dev
    python3-numpy
    python3-pip
    python3-pyte
    python3-requests
    python3-yaml
    qt6-base-dev
    qt6-base-dev-tools
    rlwrap
    ruby
    rustc
    strace
    sudo
    systemd-dev
    tar
    tcpdump
    tcsh
    tmux
    tree
    unzip
    uuid-dev
    valgrind
    vim
    virt-manager
    wireshark
    x264
    zip
    zsh
    libcsfml-*
    libcriterion
)

export DEBIAN_FRONTEND=noninteractive
apt -y install ${packages_list[@]}

clear

# Install netcat to prepare cache usage
apt update
apt install -y netcat-openbsd

# Install proxy detection
echo '#!/bin/bash
proxy=192.168.42.1
nc -zw1 $proxy 3142 && echo http://$proxy:3142/ || echo DIRECT
' > /etc/apt/detect_proxy.sh

chmod +x /etc/apt/detect_proxy.sh

echo 'Acquire::http::Proxy-Auto-Detect "/etc/apt/detect_proxy.sh";' > "/etc/apt/apt.conf.d/01acng"

# Add epitech ppa signing key and repository
rm -f /etc/apt/trusted.gpg.d/epitechppa.gpg
gpg --homedir /tmp --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/epitechppa.gpg --keyserver keyserver.ubuntu.com --recv-keys 87daad0e2657726c
chown root:root /etc/apt/trusted.gpg.d/epitechppa.gpg
chmod 644 /etc/apt/trusted.gpg.d/epitechppa.gpg
echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/epitechppa.gpg] https://ppa.launchpadcontent.net/epitech/ppa/ubuntu ./devel main" | tee /etc/apt/sources.list.d/epitechppa.list > /dev/null
echo "deb-src [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/epitechppa.gpg] https://ppa.launchpadcontent.net/epitech/ppa/ubuntu ./devel main" >> /etc/apt/sources.list.d/epitechppa.list


# Install 
echo "postfix postfix/mailname string epitech.eu" | debconf-set-selections
echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
export DEBIAN_FRONTEND=noninteractive
apt install -y epitech-dump


tput setaf 1
echo "__**/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CODING STYLE BY NOGE\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\**\*\*\*\*\**__"
echo " _           _"
echo "| |\\        | | NOGE"
echo "| |\\\       | |"
echo "| | \\\      | | EPITECH BENIN"
echo "| |  \\\     | |"
echo "| |   \\\    | | NOGE"
echo "| |    \\\   | |"
echo "| |     \\\  | | EPITECH DIGITAL SCHOOL"
echo "| |      \\\ | |"
echo "|_|       \\\|_| NOGE"
tput sgr0
