#!/bin/bash
sudo apt-get install zenity
!/bin/bash
chmod 777 *
chmod 777 src/*
chmod 777 src/epitech-emacs/*
chmod 777 src/epitech-emacs/src/*
chmod 777 src/epitech-emacs/src/epitech/*
chmod 777 src/epitech-emacs/src/site-start.d/*

if zenity --question --text="Voulez-vous installer les logiciels prérequis ?"; then
    PASSWORD=$(zenity --password --title="Mot de passe requis")
    if [ -z "$PASSWORD" ]; then
        zenity --error --text="Aucun mot de passe fourni. L'installation a été annulée."
        exit 1
    fi

    echo "$PASSWORD" | sudo -S bash ./src/script_ubuntu.sh

    if [ $? -eq 0 ]; then
        zenity --info --text="Le logiciel a été installé avec succès."
    else
        zenity --error --text="Une erreur est survenue lors de l'installation de Docker."
    fi
else
    zenity --info --text="L'installation des Logiciel a été annulée."
fi



zenity --text-info --title="Message de NOGE" --filename=./src/message.txt