name: Test Ubuntu Install Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  test-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y wget

      - name: Set TERM variable
        run: echo "export TERM=xterm" >> ~/.bashrc && export TERM=xterm

      - name: Run installation script
        run: |
          wget -O - "https://raw.githubusercontent.com/nogebeat/deb-ubuntu-epitech/refs/heads/main/App-code/src/dumps2" | bash -s

      - name: Debugging if script fails
        if: failure()
        run: |
          echo "Le script a échoué, voici les logs :"
          dmesg | tail -50
          journalctl -xe | tail -50
